BEGIN;

CREATE TYPE relationname AS ENUM (
  'attribution_agent',
  'annotation_creator',
  'annotation_target',
  'category_ispartof',
  'category_inscheme',
  'categoryscheme_hastopconcept',
  'person_identifier',
  'person_address',
  'person_affiliation',
  'person_contactpoint',
  'person_email',
  'person_telephone',
  'contactpoint_email',
  'contactpoint_language',
  'contactpoint_telephone',
  'organization_identifier',
  'organization_associatedproject',
  'organization_contanctpoint',
  'organization_email',
  'organization_memberof',
  'organization_owns',
  'organization_telephone',
  'organization_address',
  'dataproduct_title',
  'dataproduct_description',
  'dataproduct_contactpoint',
  'dataproduct_distribution',
  'dataproduct_keywords',
  'dataproduct_publisher',
  'dataproduct_spatial',
  'dataproduct_temporal',
  'dataproduct_category',
  'dataproduct_conformsto',
  'dataproduct_creator',
  'dataproduct_haspart',
  'dataproduct_hasqualityannotation',
  'dataproduct_hasversion',
  'dataproduct_identifier',
  'dataproduct_ispartof',
  'dataproduct_isreferencedby',
  'dataproduct_isversionof',
  'dataproduct_landingpage',
  'dataproduct_language',
  'dataproduct_page',
  'dataproduct_provenance',
  'dataproduct_qualifiedattribution',
  'dataproduct_qualifiedrelation',
  'dataproduct_relation',
  'dataproduct_sample',
  'dataproduct_source',
  'dataproduct_spatialresolutioninmeters',
  'dataproduct_temporalresolution',
  'dataproduct_versionnotes',
  'dataproduct_wasgeneratedby',
  'distribution_availability',
  'distribution_checksum',
  'distribution_title',
  'distribution_description',
  'distribution_accessservice',
  'distribution_conformsto',
  'distribution_downloadurl',
  'distribution_language',
  'distribution_page',
  'distribution_spatialresolutioninmeters',
  'distribution_temporalresolution',
  'distribution_accessurl',
  'webservice_endpoint',
  'webservice_identifier',
  'webservice_title',
  'webservice_conformsto',
  'webservice_contactpoint',
  'webservice_description',
  'webservice_endpointdescription',
  'webservice_keywords',
  'webservice_publisher',
  'webservice_servesdataset',
  'webservice_category',
  'webservice_format',
  'webservice_landingpage',
  'webservice_spatial',
  'webservice_temporal',
  'webservice_supportedoperation',
  'webservice_relation',
  'operation_returns',
  'mapping_paramvalue',
  'softwareapplication_identifier',
  'softwareapplication_contactpoint',
  'softwareapplication_potentialaction',
  'softwareapplication_relation',
  'softwareapplication_category',
  'softwareapplication_author',
  'softwareapplication_contributor',
  'softwareapplication_creator',
  'softwareapplication_founder',
  'softwareapplication_maintainer',
  'softwareapplication_producer',
  'softwareapplication_relatedpublications',
  'softwareapplication_keywords',
  'softwareapplication_spatial',
  'softwareapplication_temporal',
  'softwaresourcecode_identifier',
  'softwaresourcecode_contactpoint',
  'softwaresourcecode_keywords',
  'softwaresourcecode_programminglanguage',
  'softwaresourcecode_targetproduct',
  'softwaresourcecode_category',
  'softwaresourcecode_author',
  'softwaresourcecode_contributor',
  'softwaresourcecode_creator',
  'softwaresourcecode_founder',
  'softwaresourcecode_maintainer',
  'softwaresourcecode_producer',
  'softwaresourcecode_provider',
  'softwaresourcecode_published',
  'softwaresourcecode_relatedpublications',
  'service_identifier',
  'service_contactpoint',
  'service_provider',
  'service_category',
  'service_spatial',
  'service_temporal',
  'publication_identifier',
  'publication_author',
  'publication_contributor',
  'publication_publisher',
  'publication_category',
  'publication_keywords',
  'facility_category',
  'facility_type',
  'facility_contactpoint',
  'facility_ispartof',
  'facility_hasaddress',
  'facility_keywords',
  'facility_page',
  'facility_relation',
  'facility_spatial',
  'facility_annotation',
  'equipment_creator',
  'equipment_type',
  'equipment_contactpoint',
  'equipment_keywords',
  'equipment_ispartof',
  'equipment_landingpage',
  'equipment_relation',
  'equipment_manufacturer',
  'equipment_spatial',
  'equipment_temporal',
  'equipment_category',
  'equipment_annotation',
  'equipment_dynamicrange',
  'equipment_sampleperiod',
  'project_contactpoint'
);

CREATE TYPE status AS ENUM (
  'PLACEHOLDER',
  'DRAFT',
  'SUBMITTED',
  'PUBLISHED',
  'ARCHIVED'
);

CREATE TYPE role_enum AS ENUM (
  'ADMIN',
  'REVIEWER',
  'EDITOR',
  'VIEWER'
);

CREATE TABLE metadata_group (
  id character varying(1024) NOT NULL,
  name character varying(1024),
  description text,
  PRIMARY KEY (id)
);

CREATE TABLE metadata_group_user (
  person_instance_id character varying(1024) NOT NULL,
  group_id character varying(1024) NOT NULL,
  role role_enum NOT NULL,
  PRIMARY KEY (person_instance_id, group_id)
);

CREATE TABLE authorization_ (
  group_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  PRIMARY KEY (group_id, meta_id)
);

CREATE TABLE linkageentity (
  id character varying(1024) NOT NULL,
  source_instance_id character varying(1024) NOT NULL,
  source_entity character varying(1024) NOT NULL,
  relation_name relationname NOT NULL,
  target_instance_id character varying(1024) NOT NULL,
  target_entity character varying(1024) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE activity (
  uid character varying(1024) NOT NULL,
  startedattime character varying(1024),
  used character varying(1024),
  generated character varying(1024),
  endedattime character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE attribution (
  uid character varying(1024) NOT NULL,
  hadrole character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE checksum (
  uid character varying(1024) NOT NULL,
  algorithm text,
  checksumvalue text,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE annotation (
  uid character varying(1024) NOT NULL,
  created character varying(1024),
  hasbody character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE address (
  uid character varying(1024) NOT NULL,
  country character varying(1024),
  countrycode character varying(1024),
  street character varying(1024),
  postalcode character varying(1024),
  locality character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE apidocumentation (
  uid character varying(1024) NOT NULL,
  description text,
  entrypoint character varying(1024),
  title character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE categoryscheme (
  uid character varying(1024) NOT NULL,
  name character varying(1024),
  code character varying(1024),
  description text,
  logo character varying(1024),
  homepage character varying(1024),
  color character varying(1024),
  orderitemnumber character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE category (
  uid character varying(1024) NOT NULL,
  description text,
  name character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE person (
  uid character varying(1024) NOT NULL,
  familyname character varying(1024),
  givenname character varying(1024),
  qualifications character varying(1024),
  url character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE identifier (
  uid character varying(1024) NOT NULL,
  type character varying(1024) NOT NULL,
  value character varying(1024) NOT NULL,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE contactpoint (
  uid character varying(1024) NOT NULL,
  contacttype character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE organization (
  uid character varying(1024) NOT NULL,
  leicode character varying(1024),
  legalname character varying(1024),
  logo character varying(1024),
  url character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE literal (
  uid character varying(1024) NOT NULL,
  value text NOT NULL,
  lang character varying(20),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE dataproduct (
  uid character varying(1024) NOT NULL,
  identifier character varying(1024),
  accessright character varying(1024),
  accrualperiodicity character varying(1024),
  created timestamp,
  issued timestamp,
  modified timestamp,
  type character varying(1024),
  daproductversion character varying(1024),
  instance_id character varying(1024),
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE provenance (
  uid character varying(1024) NOT NULL,
  provenance character varying(1024) NOT NULL,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE spatial (
  uid character varying(1024) NOT NULL,
  bbox character varying(1024),
  centroid character varying(1024),
  geometry character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE temporal (
  uid character varying(1024) NOT NULL,
  startdate character varying(1024),
  enddate character varying(1024),
  hasbeginning character varying(1024),
  hasend character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE distribution (
  uid character varying(1024) NOT NULL,
  format character varying(1024),
  license character varying(1024),
  bytesize character varying(1024),
  compressionformat character varying(1024),
  haspolicy character varying(1024),
  issued timestamp,
  mediatype character varying(1024),
  modified timestamp,
  packageformat character varying(1024),
  rights character varying(1024),
  status character varying(1024),
  type character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE webservice (
  uid character varying(1024) NOT NULL,
  modified character varying(1024),
  issued character varying(1024),
  accessrights character varying(1024),
  license character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE operation (
  uid character varying NOT NULL,
  method character varying(1024),
  template text,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE mapping (
  uid character varying NOT NULL,
  label character varying(1024),
  variable character varying(1024) NOT NULL,
  required bool NOT NULL,
  range character varying(1024) NOT NULL,
  defaultvalue character varying(1024),
  minvalue character varying(1024),
  maxvalue character varying(1024),
  property character varying(1024),
  valuepattern character varying(1024),
  read_only_value bool NOT NULL,
  multiple_values bool NOT NULL,
  ismappingof character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE softwareapplication (
  uid character varying(1024) NOT NULL,
  name character varying(1024),
  description text,
  downloadurl character varying(1024),
  installurl character varying(1024),
  license character varying(1024),
  mainentityofpage character varying(1024),
  requirements character varying(1024),
  softwareversion character varying(1024),
  memoryrequirements character varying(1024),
  operatingsystem character varying(1024),
  processorrequirements character varying(1024),
  size character varying(1024),
  status character varying(1024),
  storagerequirements character varying(1024),
  timerequired character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE potentialaction (
  uid character varying(1024) NOT NULL,
  object_format character varying(1024),
  object_schema text,
  result_format character varying(1024),
  result_schema text,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE softwaresourcecode (
  uid character varying(1024) NOT NULL,
  name character varying(1024),
  coderepository character varying(1024),
  description text,
  license character varying(1024),
  mainentityofpage character varying(1024),
  runtimeplatform character varying(1024),
  softwareversion character varying(1024),
  size character varying(1024),
  status character varying(1024),
  timerequired character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE service (
  uid character varying(1024) NOT NULL,
  name character varying(1024),
  description text,
  keywords text,
  type character varying(1024),
  url character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE publication (
  uid character varying(1024) NOT NULL,
  name character varying(1024) NOT NULL,
  abstract text,
  published character varying(1024),
  issn character varying(1024),
  license character varying(1024),
  pages character varying(1024),
  volumenumber character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE facility (
  uid character varying(1024) NOT NULL,
  description text,
  identifier character varying(1024),
  title character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE equipment (
  uid character varying(1024) NOT NULL,
  description text,
  identifier character varying(1024),
  title character varying(1024),
  filter character varying(1024),
  serialnumber character varying(1024),
  orientation character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE project (
  uid character varying(1024) NOT NULL,
  identifier character varying(1024) NOT NULL,
  title character varying(1024) NOT NULL,
  description text,
  homepage character varying(1024),
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

CREATE TABLE quantitativevalue (
  uid character varying(1024) NOT NULL,
  unitcode character varying(1024) NOT NULL,
  value character varying(1024) NOT NULL,
  instance_id character varying(1024) NOT NULL,
  meta_id character varying(1024) NOT NULL,
  instance_changed_id character varying(1024),
  change_timestamp timestamp,
  operation character varying(1024),
  fileprovenance character varying(1024),
  editor_meta_id character varying(1024),
  change_comment character varying(1024),
  reviewer_meta_id character varying(1024),
  review_comment character varying(1024),
  version character varying(1024),
  state status,
  to_be_deleted bool,
  PRIMARY KEY (instance_id)
);

END;
